int stok(char *str, char delim, char *ptr[], int size);
int schr(char *str, char delim, int size);
void suntok(char *str, char delim, char *ptr[], int cnt);
int slen(char *str);
char toLowCase(char *str, int size);
int isIp(char *ptr[], int size, int t);
void check(char *str, char *ptr[], int size);
void process(char *str, int size);
void input(char *str);
void output(char *str);
int scspn(char str[], int size);
